import { Inter } from "next/font/google";
import "./globals.css";
import Leftbar from "@/components/Leftbar";
import Rightbar from "@/components/Rightbar";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <Leftbar/>
        <Rightbar/>
      <div className="w-[70%] relative top-10 left-[15%] pb-12">
      {children}
      </div>
        <footer className="w-full bg-red-400 text-center h-10">
          This is Footer
        </footer>
        </body>
    </html>
  );
}
